-- =====================================================================
--  DeineFenster.de — Seed-Daten: 24 Demo-Produkte
--  Stand: 27.04.2026
--
--  ANLEITUNG (optional, nur für Demo):
--    Wie schon das Schema-Skript: SQL Editor → New query → reinkopieren → Run.
--    Du kriegst dann 24 realistische Lagerware-Beispiele in den Shop —
--    perfekt um die Filter, Suche und das Layout durchzuspielen.
--    Wenn du eigene Produkte einstellst, kannst du diese hier später
--    löschen oder einzeln entfernen.
-- =====================================================================

insert into public.produkte
  (titel, kategorie_key, system, breite_mm, hoehe_mm, preis_eur, farbe, verglasung, u_wert, oeffnungsart, rc_klasse, eigenschaften, lagerbestand, bilder, beschreibung)
values
  ('Drutex Kunststofffenster Einflügelig 600 × 800 mm Weiß', 'fenster-1fluegel', 'IGLO 5 Classic', 600, 800, 189, 'weiss', '2-fach', 0.83, 'dreh-kipp', null, '["dreh-kipp","2-fach-verglasung"]'::jsonb, 4, '["img/fenster_standard.png"]'::jsonb, 'Solides Drutex IGLO 5 Classic Einflügelfenster mit Dreh-Kipp-Funktion. Ideal für Wohnräume in Standardgröße.'),
  ('Drutex Fenster 800 × 1000 mm Weiß IGLO 5 Classic', 'fenster-1fluegel', 'IGLO 5 Classic', 800, 1000, 249, 'weiss', '2-fach', 0.83, 'dreh-kipp', null, '["dreh-kipp","2-fach-verglasung"]'::jsonb, 6, '["img/fenster_standard.png"]'::jsonb, 'Klassisches Drutex Einflügelfenster für Schlafzimmer und Wohnzimmer. Sofort lieferbar.'),
  ('Drutex IGLO Energy 1000 × 1200 mm Anthrazit 3-fach', 'fenster-1fluegel', 'IGLO Energy', 1000, 1200, 419, 'anthrazit', '3-fach', 0.71, 'dreh-kipp', 'RC2', '["dreh-kipp","3-fach-verglasung","rc2","passivhaus-tauglich"]'::jsonb, 2, '["img/fenster-1fluegel-aussen.png"]'::jsonb, 'Premium-Energiesparfenster mit Anthrazit-Außendekor. RC2-Sicherheit, passivhaus-tauglich.'),
  ('Drutex Fenster 1200 × 1400 mm Weiß IGLO Energy 3-fach', 'fenster-1fluegel', 'IGLO Energy', 1200, 1400, 489, 'weiss', '3-fach', 0.71, 'dreh-kipp', 'RC2', '["dreh-kipp","3-fach-verglasung","rc2","passivhaus-tauglich"]'::jsonb, 3, '["img/fenster_standard.png"]'::jsonb, 'Wohnzimmerfenster mit 3-fach-Verglasung. Passivhaus-tauglich, RC2-Sicherheit.'),
  ('Drutex Zweiflügelfenster 1400 × 1400 mm Weiß Stulp', 'fenster-2fluegel', 'IGLO 5 Classic', 1400, 1400, 469, 'weiss', '2-fach', 0.83, 'stulp', null, '["stulp","2-fach-verglasung"]'::jsonb, 3, '["img/fenster-2fluegel-aussen.png"]'::jsonb, 'Zweiflügelfenster mit Stulpprofil — kein störender Mittelpfosten. Maximale Lichtausbeute.'),
  ('Drutex IGLO Energy 1600 × 1400 mm Anthrazit Pfosten', 'fenster-2fluegel', 'IGLO Energy', 1600, 1400, 719, 'anthrazit', '3-fach', 0.71, 'pfosten', 'RC2', '["pfosten","3-fach-verglasung","rc2"]'::jsonb, 2, '["img/fenster-2fluegel-aussen.png"]'::jsonb, 'Großes Wohnzimmerfenster, anthrazit, mit Mittelpfosten — robust und einbruchhemmend (RC2).'),
  ('Drutex Dreiflügelfenster 1800 × 1400 mm Weiß', 'fenster-3fluegel', 'IGLO 5 Classic', 1800, 1400, 599, 'weiss', '2-fach', 0.83, 'dreh-kipp', null, '["dreh-kipp","2-fach-verglasung"]'::jsonb, 1, '["img/fenster-aussen-3fluegel.png"]'::jsonb, 'Großes Dreiflügelfenster für lichtdurchflutete Räume. Mittlerer Flügel fest, Außenflügel Dreh-Kipp.'),
  ('Drutex Vierflügelfenster 2400 × 1400 mm Weiß', 'fenster-4fluegel', 'IGLO Energy', 2400, 1400, 899, 'weiss', '3-fach', 0.71, 'dreh-kipp', 'RC2', '["dreh-kipp","3-fach-verglasung","rc2"]'::jsonb, 1, '["img/fenster-aussen-4fluegel.png"]'::jsonb, 'Großzügiges Vierflügelfenster für Wintergarten oder Wohnzimmer. Premium-Wärmedämmung.'),
  ('Drutex Festverglasung 1000 × 500 mm Weiß', 'festelement', 'IGLO 5 Classic', 1000, 500, 139, 'weiss', '2-fach', 0.83, 'fest', null, '["festverglasung","2-fach-verglasung"]'::jsonb, 5, '["img/fenster_standard.png"]'::jsonb, 'Festverglastes Element für Treppenhaus, Bad oder als Lichtband. Nicht öffenbar.'),
  ('Drutex Festelement 1500 × 800 mm Anthrazit IGLO Energy', 'festelement', 'IGLO Energy', 1500, 800, 309, 'anthrazit', '3-fach', 0.71, 'fest', null, '["festverglasung","3-fach-verglasung"]'::jsonb, 2, '["img/fenster_standard.png"]'::jsonb, 'Großes Festelement in Anthrazit. Perfekt als Schaufenster oder Panoramablick im Wohnzimmer.'),
  ('Drutex Kellerfenster 500 × 400 mm Weiß', 'kellerfenster', 'IGLO 5 Classic', 500, 400, 99, 'weiss', '2-fach', 0.83, 'dreh-kipp', null, '["dreh-kipp","2-fach-verglasung","kompaktmass"]'::jsonb, 12, '["img/fenster_standard.png"]'::jsonb, 'Kompaktes Kellerfenster mit Dreh-Kipp. Standardmaß für Bestandsbauten.'),
  ('Drutex Kellerfenster 600 × 500 mm Weiß', 'kellerfenster', 'IGLO 5 Classic', 600, 500, 119, 'weiss', '2-fach', 0.83, 'dreh-kipp', null, '["dreh-kipp","2-fach-verglasung","kompaktmass"]'::jsonb, 8, '["img/fenster_standard.png"]'::jsonb, 'Kellerfenster, Standardgröße. Sofort lieferbar — perfekt für Sanierung.'),
  ('Drutex Kellerfenster 800 × 600 mm Weiß', 'kellerfenster', 'IGLO 5 Classic', 800, 600, 149, 'weiss', '2-fach', 0.83, 'dreh-kipp', null, '["dreh-kipp","2-fach-verglasung","kompaktmass"]'::jsonb, 6, '["img/fenster_standard.png"]'::jsonb, 'Kellerfenster im 4:3 Format. Bequeme Lüftung über Kippstellung.'),
  ('Drutex Balkontür Einflügelig 900 × 2200 mm Weiß', 'balkontuer-1fluegel', 'IGLO 5 Classic', 900, 2200, 599, 'weiss', '2-fach', 0.83, 'dreh-kipp', null, '["dreh-kipp","2-fach-verglasung","alu-schwelle"]'::jsonb, 3, '["img/balkontuer_standard.png"]'::jsonb, 'Klassische Balkontür mit Alu-Schwelle. Dreh-Kipp-Funktion, Standardmaß.'),
  ('Drutex Balkontür Zweiflügelig 1600 × 2200 mm Anthrazit', 'balkontuer-2fluegel', 'IGLO Energy', 1600, 2200, 1199, 'anthrazit', '3-fach', 0.71, 'stulp', 'RC2', '["stulp","3-fach-verglasung","rc2","alu-schwelle"]'::jsonb, 1, '["img/balkontuer_standard.png"]'::jsonb, 'Premium-Balkontür zweiflüglig anthrazit. Stulpprofil ohne Mittelpfosten, RC2-Sicherheit.'),
  ('Drutex Balkontür mit Rollladen 900 × 2200 mm Weiß', 'balkontuer-rollo', 'IGLO 5 Classic', 900, 2200, 819, 'weiss', '2-fach', 0.83, 'dreh-kipp', null, '["dreh-kipp","2-fach-verglasung","rollladen-elektrisch","alu-schwelle"]'::jsonb, 2, '["img/balkontuer_standard.png"]'::jsonb, 'Balkontür mit elektrischem Aufsatzrollladen. Sofort einbau-fertig inkl. Funkmotor.'),
  ('Drutex PSK Schiebetür 2400 × 2200 mm Weiß IGLO 5', 'schiebetuer-psk', 'IGLO 5 Classic PSK', 2400, 2200, 2299, 'weiss', '3-fach', 0.81, 'psk', null, '["parallel-schiebe-kipp","3-fach-verglasung","alu-schwelle"]'::jsonb, 1, '["img/hst_standard.png"]'::jsonb, 'Parallel-Schiebe-Kipp-Tür für Terrasse oder Balkon. Komfortable Bedienung, kompakte Bauweise.'),
  ('Drutex IGLO-HS 4000 × 2400 mm Anthrazit Hebe-Schiebe', 'schiebetuer-hst', 'IGLO-HS', 4000, 2400, 4899, 'anthrazit', '3-fach', 0.71, 'hebe-schiebe', 'RC2', '["hebe-schiebe","3-fach-verglasung","rc2","null-schwelle","barrierefrei"]'::jsonb, 1, '["img/hst_standard.png"]'::jsonb, 'Premium Hebe-Schiebe-Tür IGLO-HS in Anthrazit. Null-Schwelle nach DIN 18040, barrierefrei.'),
  ('Drutex Haustür DX-07 Anthrazit 1100 × 2100 mm', 'haustuer', 'IGLO 5 Classic Tür', 1100, 2100, 1899, 'anthrazit', '3-fach', 1.0, 'drehfluegel', 'RC2', '["edelstahl-stossgriff","3-fach-verglasung","rc2","5-fach-verriegelung"]'::jsonb, 1, '["img/dx07.png"]'::jsonb, 'Designhaustür DX-07 in Anthrazit. Edelstahl-Stoßgriff, 5-fach-Verriegelung, RC2.'),
  ('Drutex Haustür DX-23 Weiß 1000 × 2000 mm', 'haustuer', 'IGLO 5 Classic Tür', 1000, 2000, 1599, 'weiss', '3-fach', 1.0, 'drehfluegel', 'RC2', '["edelstahl-stossgriff","3-fach-verglasung","rc2","5-fach-verriegelung"]'::jsonb, 2, '["img/dx23.png"]'::jsonb, 'Designhaustür DX-23 in Weiß. Modernes klares Design mit Edelstahl-Akzenten.'),
  ('Drutex Haustür Texas Anthrazit 1100 × 2100 mm', 'haustuer', 'IGLO 5 Classic Tür', 1100, 2100, 1799, 'anthrazit', '3-fach', 1.0, 'drehfluegel', 'RC2', '["3-fach-verglasung","rc2","5-fach-verriegelung"]'::jsonb, 1, '["img/texas.png"]'::jsonb, 'Klassische Haustür Texas in Anthrazit — rustikal, mit dezenten Glasausschnitten.'),
  ('Drutex Fenster mit Oberlicht 1200 × 1800 mm Weiß', 'fenster-oberlicht', 'IGLO 5 Classic', 1200, 1800, 599, 'weiss', '2-fach', 0.83, 'dreh-kipp', null, '["dreh-kipp","2-fach-verglasung","oberlicht"]'::jsonb, 2, '["img/fenster-aussen-3fluegel.png"]'::jsonb, 'Fenster mit feststehendem Oberlicht — klassische Altbau-Optik, modern umgesetzt.'),
  ('Drutex Sprossenfenster 1000 × 1200 mm Golden Oak', 'fenster-sprossen', 'IGLO 5 Classic', 1000, 1200, 479, 'golden-oak', '2-fach', 0.83, 'dreh-kipp', null, '["dreh-kipp","2-fach-verglasung","sprossen-aufgesetzt","holzdekor"]'::jsonb, 2, '["img/fenster_standard.png"]'::jsonb, 'Sprossenfenster im Holzdekor Golden Oak. Aufgesetzte Sprossen für Landhaus-Charakter.');

-- Fertig. 24 Demo-Produkte sollten jetzt in der Tabelle stehen.
-- Prüfen: Supabase → "Table Editor" → produkte → 24 Zeilen sichtbar.
